// export const productData = {
//   marble: {
//     'white-marble': {
//       name: "White Marble",
//       priceFrom: 60,
//       priceTo: 95,
//       moq: 1500,
//       image: "",
//       businessType: "Manufacturer, Exporter",
//       material: "Marble",
//       shape: "Rectangular",
//       application: "Flooring, Wall Cladding",
//       feature: "Polished, Elegant Look",
//       thickness: "16 MM To 20 MM",
//       surface: "Polished, Matte",
//       origin: "India"
//     },
//     'black-marble': {
//       name: "Black Marble",
//       priceFrom: 65,
//       priceTo: 100,
//       moq: 1200,
//       image: "",
//       businessType: "Supplier",
//       material: "Marble",
//       shape: "Rectangular",
//       application: "Countertops, Bathrooms",
//       feature: "Shiny, Durable",
//       thickness: "18 MM",
//       surface: "Polished",
//       origin: "India"
//     },
//     'pink-marble': {
//       name: "Pink Marble",
//       priceFrom: 55,
//       priceTo: 85,
//       moq: 1300,
//       image: "",
//       businessType: "Manufacturer",
//       material: "Marble",
//       shape: "Slab",
//       application: "Interior Walls",
//       feature: "Attractive Color, Smooth Finish",
//       thickness: "15 MM To 18 MM",
//       surface: "Honed",
//       origin: "India"
//     },
//     'green-marble': {
//       name: "Green Marble",
//       priceFrom: 50,
//       priceTo: 90,
//       moq: 1400,
//       image: "",
//       businessType: "Exporter",
//       material: "Marble",
//       shape: "Tile",
//       application: "Flooring",
//       feature: "Natural Color, Anti-Slip",
//       thickness: "16 MM",
//       surface: "Matte",
//       origin: "India"
//     }
//   },
//   'importedmarble': {
//     italian: {
//       name: "Italian Marble",
//       priceFrom: 120,
//       priceTo: 180,
//       moq: 2000,
//       image: "",
//       businessType: "Importer, Supplier",
//       material: "Marble",
//       shape: "Slab",
//       application: "Luxury Flooring",
//       feature: "Premium Shine, High Strength",
//       thickness: "20 MM",
//       surface: "Polished",
//       origin: "Italy"
//     },
//     spanish: {
//       name: "Spanish Marble",
//       priceFrom: 110,
//       priceTo: 170,
//       moq: 1800,
//       image: "",
//       businessType: "Importer",
//       material: "Marble",
//       shape: "Rectangular",
//       application: "Interiors",
//       feature: "Elegant Texture",
//       thickness: "18 MM",
//       surface: "Polished",
//       origin: "Spain"
//     },
//     turkish: {
//       name: "Turkish Marble",
//       priceFrom: 95,
//       priceTo: 160,
//       moq: 1700,
//       image: "",
//       businessType: "Supplier",
//       material: "Marble",
//       shape: "Slab",
//       application: "Wall Cladding",
//       feature: "Natural Finish, Rich Texture",
//       thickness: "16 MM",
//       surface: "Polished",
//       origin: "Turkey"
//     }
//   },
//   granite: {
//     'red-granite': {
//       name: "Red Granite",
//       priceFrom: 70,
//       priceTo: 100,
//       moq: 2200,
//       image: "",
//       businessType: "Manufacturer",
//       material: "Granite",
//       shape: "Tile",
//       application: "Exterior Cladding",
//       feature: "Durable, Scratch Resistant",
//       thickness: "18 MM",
//       surface: "Flamed",
//       origin: "India"
//     },
//     'black-galaxy': {
//       name: "Black Galaxy",
//       priceFrom: 85,
//       priceTo: 115,
//       moq: 2500,
//       image: "",
//       businessType: "Exporter",
//       material: "Granite",
//       shape: "Slab",
//       application: "Kitchen Countertops",
//       feature: "Sparkling Surface",
//       thickness: "18 MM",
//       surface: "Polished",
//       origin: "India"
//     },
//     'kashmir-white': {
//       name: "Kashmir White",
//       priceFrom: 75,
//       priceTo: 105,
//       moq: 2300,
//       image: "",
//       businessType: "Supplier",
//       material: "Granite",
//       shape: "Rectangular",
//       application: "Floors and Walls",
//       feature: "Elegant, Long-Lasting",
//       thickness: "16 MM",
//       surface: "Polished",
//       origin: "India"
//     }
//   },
//   sandstone: {
//     teakwood: {
//       name: "Teakwood Sandstone",
//       priceFrom: 45,
//       priceTo: 75,
//       moq: 1600,
//       image: "",
//       businessType: "Manufacturer",
//       material: "Sandstone",
//       shape: "Tile",
//       application: "Wall Cladding, Exterior",
//       feature: "Natural Finish, Unique Grain",
//       thickness: "20 MM",
//       surface: "Natural",
//       origin: "India"
//     },
//     rainbow: {
//       name: "Rainbow Sandstone",
//       priceFrom: 50,
//       priceTo: 80,
//       moq: 1700,
//       image: "",
//       businessType: "Exporter",
//       material: "Sandstone",
//       shape: "Slab",
//       application: "Garden Path, Exterior",
//       feature: "Colorful Stripes",
//       thickness: "20 MM",
//       surface: "Sawn",
//       origin: "India"
//     },
//     dholpur: {
//       name: "Dholpur Sandstone",
//       priceFrom: 40,
//       priceTo: 70,
//       moq: 1500,
//       image: "",
//       businessType: "Supplier",
//       material: "Sandstone",
//       shape: "Block",
//       application: "Heritage Building",
//       feature: "Durable, Heritage Look",
//       thickness: "22 MM",
//       surface: "Rough",
//       origin: "India"
//     }
//   },
//   tiles: {
//     ceramic: {
//       name: "Ceramic Tile",
//       priceFrom: 25,
//       priceTo: 45,
//       moq: 1000,
//       image: "",
//       businessType: "Manufacturer",
//       material: "Ceramic",
//       shape: "Square",
//       application: "Interior Flooring",
//       feature: "Glossy, Water-Resistant",
//       thickness: "10 MM",
//       surface: "Glossy",
//       origin: "India"
//     },
//     porcelain: {
//       name: "Porcelain Tile",
//       priceFrom: 35,
//       priceTo: 55,
//       moq: 1200,
//       image: "",
//       businessType: "Supplier",
//       material: "Porcelain",
//       shape: "Rectangular",
//       application: "Bathroom, Kitchen",
//       feature: "Durable, Non-Slip",
//       thickness: "12 MM",
//       surface: "Matte",
//       origin: "India"
//     },
//     vitrified: {
//       name: "Vitrified Tile",
//       priceFrom: 30,
//       priceTo: 50,
//       moq: 1300,
//       image: "",
//       businessType: "Exporter",
//       material: "Vitrified",
//       shape: "Square",
//       application: "Commercial Flooring",
//       feature: "High Gloss, Anti-Stain",
//       thickness: "10 MM",
//       surface: "Glossy",
//       origin: "India"
//     }
//   }
// };





export const productData = {
  "marble": {
    "makrana-pink": {
      "name": "Makrana Pink",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring",
      "feature": "Polished, unpolished",
      "thickness": "14mm, 15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "silver-storm": {
      "name": "Silver Storm",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Exterior cladding, wall elevation",
      "feature": "Hydro finish",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "burberry-grey": {
      "name": "Burberry Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, staircase",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "bulberry-grey": {
      "name": "Bulberry grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring, staircase",
      "feature": "Unpolished",
      "thickness": "18mm, 20mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "opus-white": {
      "name": "Opus white",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring, furniture, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "wonder-white": {
      "name": "Wonder white",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring, furniture, head wall cladding, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm, 20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "gold-fire": {
      "name": "Gold Fire",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, furniture, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "red-allicante": {
      "name": "Red Allicante",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, furniture, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Belgium"
    },
    "golden-portro": {
      "name": "Golden Portro",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "meteorite": {
      "name": "Meteorite",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, furniture, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "India"
    },
    "dover-white": {
      "name": "Dover White",
      "priceFrom": 600,
      "priceTo": 700,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Africa"
    },
    "silver-stream": {
      "name": "Silver Stream",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, exterior cladding, flooring, furniture, head wall cladding, highlighter wall, staircase, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "thasos-white": {
      "name": "Thasos White",
      "priceFrom": 1500,
      "priceTo": 2000,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Greece"
    },
    "marmara-white": {
      "name": "Marmara White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, exterior cladding, flooring",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "night-black": {
      "name": "Night Black",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "pink-valentine": {
      "name": "Pink Valentine",
      "priceFrom": 600,
      "priceTo": 700,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "indian-avocado-green": {
      "name": "Indian Avocado Green",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Hydro finish",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "african-brown": {
      "name": "African brown",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Iran"
    },
    "marrone-grigio": {
      "name": "Marrone Grigio",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "rosso-paceto": {
      "name": "Rosso Paceto",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, head wall cladding, highlighter wall, staircase, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "katni-beige": {
      "name": "Katni Beige",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "14mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "aramis-white": {
      "name": "Aramis White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "macedonia-white": {
      "name": "Macedonia white",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, staircase, wall elevation",
      "feature": "Unpolished",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Greece"
    },
    "golden-spider": {
      "name": "Golden Spider",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "tundra-grey": {
      "name": "Tundra Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "bianco-lassa-white": {
      "name": "Bianco Lassa White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Vietnam"
    },
    "pietra-grey": {
      "name": "Pietra Grey",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Iran"
    },
    "silver-chiffon": {
      "name": "Silver Chiffon",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "bellissimo-beige": {
      "name": "Bellissimo Beige",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "brescia-beige": {
      "name": "Brescia Beige",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "grigio-oro": {
      "name": "Grigio Oro",
      "priceFrom": 600,
      "priceTo": 700,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, head wall cladding, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Africa"
    },
    "camouflage-white": {
      "name": "Camouflage White",
      "priceFrom": 1000,
      "priceTo": 1500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Albania"
    },
    "camouflage-beige": {
      "name": "Camouflage Beige",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Albania"
    },
    "silver-portro": {
      "name": "Silver Portro",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "China"
    },
    "black-rose": {
      "name": "Black Rose",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Iran"
    },
    "spider-white": {
      "name": "Spider White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Iran"
    },
    "dark-emperador": {
      "name": "Dark Emperador",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Spain"
    },
    "fusion-spider": {
      "name": "Fusion Spider",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "burberry-beige": {
      "name": "Burberry Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "grey-william": {
      "name": "Grey William",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Indian, turkey"
    },
    "vietnam-white-(fine-crystal)": {
      "name": "Vietnam White (Fine Crystal)",
      "priceFrom": 1000,
      "priceTo": 1500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Vietnam"
    },
    "vietnam-white-(medium-crystal)": {
      "name": "Vietnam White (Medium Crystal)",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Vietnam"
    },
    "venetino-white": {
      "name": "Venetino White",
      "priceFrom": 600,
      "priceTo": 700,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "michelangelo": {
      "name": "Michelangelo",
      "priceFrom": 1000,
      "priceTo": 1500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm, 20mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "vietnam-white-(-large-crystal)": {
      "name": "Vietnam White ( large crystal)",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Vietnam"
    },
    "silver-dolomite": {
      "name": "Silver Dolomite",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "nsl-black": {
      "name": "NSL Black",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "black-marquina": {
      "name": "Black Marquina",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Spain"
    },
    "dyna-beige": {
      "name": "Dyna Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "bottochino-beige": {
      "name": "Bottochino Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "fantasy-grey": {
      "name": "Fantasy Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "volakas-white": {
      "name": "Volakas White",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Greece"
    },
    "iceberg-grey": {
      "name": "Iceberg Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "cosmic-grey": {
      "name": "Cosmic Grey",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "silver-river": {
      "name": "Silver River",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "castle-grey": {
      "name": "Castle Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "moon-stone": {
      "name": "Moon Stone",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "iranian-white": {
      "name": "Iranian White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Iran"
    },
    "cappuccino-brown": {
      "name": "Cappuccino Brown",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "regal-beige": {
      "name": "Regal Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "michelangelo-zambia": {
      "name": "Michelangelo Zambia",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Zambia"
    },
    "grey-dyna": {
      "name": "Grey Dyna",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "bianco-carrara": {
      "name": "Bianco Carrara",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "belgian-black": {
      "name": "Belgian Black",
      "priceFrom": 800,
      "priceTo": 900,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Belgium"
    },
    "red-merlot": {
      "name": "Red Merlot",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, furniture, head wall cladding, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "furo-depesco": {
      "name": "Furo Depesco",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Europe"
    },
    "opera-fantasy.": {
      "name": "Opera Fantasy.",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Europe"
    },
    "rustic--brown": {
      "name": "Rustic  Brown",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Europe"
    },
    "signature-white": {
      "name": "Signature White",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "grey-bardilo": {
      "name": "Grey Bardilo",
      "priceFrom": 600,
      "priceTo": 700,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, head wall cladding, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "venice-grey": {
      "name": "Venice Grey",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "civic-white": {
      "name": "Civic White",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "calacatta-statuario": {
      "name": "Calacatta Statuario",
      "priceFrom": 1000,
      "priceTo": 1500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "azule-beige": {
      "name": "Azule Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "symphony-grey": {
      "name": "Symphony Grey",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "vanilla-silver": {
      "name": "Vanilla Silver",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "agora-beige": {
      "name": "Agora Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "afghan-white": {
      "name": "Afghan White",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Afghanistan"
    },
    "tola-tina": {
      "name": "Tola Tina",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Spain"
    },
    "sugar-beige": {
      "name": "Sugar Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "sicilia-perlato": {
      "name": "Sicilia Perlato",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "lilac-white": {
      "name": "Lilac White",
      "priceFrom": 500,
      "priceTo": 600,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "silver-horizon": {
      "name": "Silver Horizon",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring, staircase, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "swiss-white": {
      "name": "Swiss White",
      "priceFrom": 1000,
      "priceTo": 1500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "sofita-beige": {
      "name": "Sofita Beige",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "armani-bronze": {
      "name": "Armani bronze",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, head wall cladding, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Spain"
    },
    "gregio-arctico": {
      "name": "Gregio Arctico",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, head wall cladding, highlighter wall, staircase, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    },
    "black-&-gold": {
      "name": "Black & Gold",
      "priceFrom": 300,
      "priceTo": 400,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, furniture, highlighter wall, wall elevation",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Spain"
    },
    "black-wave": {
      "name": "Black Wave",
      "priceFrom": 400,
      "priceTo": 500,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Countertops, flooring, head wall cladding, highlighter wall",
      "feature": "Unpolished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Italian"
    },
    "crema-marfil": {
      "name": "Crema Marfil",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "Marble",
      "shape": "",
      "application": "Flooring",
      "feature": "Unpolished",
      "thickness": "16mm, 18mm",
      "surface": "Polished, Matte",
      "origin": "Turkey"
    }
  },
  "granite": {
    "emerald-pearl": {
      "name": "Emerald Pearl",
      "priceFrom": 700,
      "priceTo": 800,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "Countertops",
      "feature": "Polished",
      "thickness": "18mm",
      "surface": "Polished, Matte",
      "origin": "Norway"
    },
    "marine-black": {
      "name": "Marine Black",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "Countertops, flooring, wall elevation",
      "feature": "Polished",
      "thickness": "16mm, 18mm, 20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "titanium-black": {
      "name": "Titanium Black",
      "priceFrom": 200,
      "priceTo": 300,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Hydro finish",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "r-black": {
      "name": "R Black",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "lakha-red": {
      "name": "Lakha Red",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "viscon-white": {
      "name": "Viscon White",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "alaska-gold": {
      "name": "Alaska Gold",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "alaska-blue-dunes": {
      "name": "Alaska Blue dunes",
      "priceFrom": 100,
      "priceTo": 200,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "20mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "s-white": {
      "name": "S-White",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "cat-eyes-brown": {
      "name": "Cat-eyes Brown",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "pearl-black": {
      "name": "Pearl Black",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "gem-red": {
      "name": "Gem Red",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "devda-green": {
      "name": "Devda Green",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "chima-pink": {
      "name": "Chima Pink",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    },
    "p-white": {
      "name": "P White",
      "priceFrom": 0,
      "priceTo": 100,
      "moq": 0,
      "image": "",
      "businessType": "",
      "material": "granite",
      "shape": "",
      "application": "",
      "feature": "Polished",
      "thickness": "15mm",
      "surface": "Polished, Matte",
      "origin": "Indian"
    }
  },
}